Version 1.4.1
sbaerlocher/ansible.ntp pull request #6
Opened 2019-07-02 11:06 UTC by sbaerlocher

- Update Syntax, Code and Documentaion
- Fix More Server by Windows

2019-07-02 11:29 UTC, ndum reviewed
Approved

2019-07-18 13:14 UTC, FreeMinded requested changes
Changelog.md line 14 should say
- Fixed Problem that only one NTP server could be specified.

2019-07-19 14:15 UTC, mleutenegger commented on tasks/main.yml
> +        - '{{ distribution }}-{{ distribution_verion }}.yml'
```suggestion
        - '{{ distribution }}-{{ distribution_version }}.yml'
```

2019-07-19 14:15 UTC, mleutenegger commented on tasks/main.yml
> +        - '{{ distribution }}-{{ distribution_verion }}.yml'
```suggestion
        - '{{ distribution }}-{{ distribution_version }}.yml'
```

2019-07-19 14:15 UTC, mleutenegger commented on tasks/main.yml
> +    distribution_verion: '{{ ansible_distribution_version }}'
```suggestion
    distribution_version: '{{ ansible_distribution_version }}'
```

2019-07-19 14:16 UTC, mleutenegger commented on tasks/main.yml
> +    distribution_verion: '{{ ansible_distribution_version }}'
```suggestion
    distribution_version: '{{ ansible_distribution_version }}'
```

2019-07-19 15:45 UTC, mleutenegger approved these changes

2019-07-21 09:41 UTC, FreeMinded approved these changes

2019-07-21 14:16 UTC, merged